// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjVw25pDN3IsKaDw2YBf6RkDS5N6xfixg',
    appId: '1:388949028952:web:a2e12abab4bf77d55ada2d',
    messagingSenderId: '388949028952',
    projectId: 'test-eec0f',
    authDomain: 'test-eec0f.firebaseapp.com',
    databaseURL: 'https://test-eec0f.firebaseio.com',
    storageBucket: 'test-eec0f.appspot.com',
    measurementId: 'G-J5QCX6L7VM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAw7m2XsUAxbFfqJErnseqBFbKwRgD6U3Y',
    appId: '1:388949028952:android:7e6b6643f199a2325ada2d',
    messagingSenderId: '388949028952',
    projectId: 'test-eec0f',
    databaseURL: 'https://test-eec0f.firebaseio.com',
    storageBucket: 'test-eec0f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANFrdhlPX3omMSMJsdM0y0T6ws7t0110Y',
    appId: '1:388949028952:ios:6846651d1ef7c9135ada2d',
    messagingSenderId: '388949028952',
    projectId: 'test-eec0f',
    databaseURL: 'https://test-eec0f.firebaseio.com',
    storageBucket: 'test-eec0f.appspot.com',
    iosClientId: '388949028952-t4pk1fvqujpa38bpv8qks7dtthnd52k5.apps.googleusercontent.com',
    iosBundleId: 'pteSupport',
  );
}
